"""Figures — the existing matplotlib gallery (figures/output/*.png). No
reason to rebuild these as interactive charts; they already work well as
static single-day visual summaries."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

import data
import theme

st.title("🖼️ Figures")
st.caption("Generated by `figures/generate()` at the end of every run — reflects the most recent run's date.")

@st.fragment(run_every=theme.auto_refresh_interval())
def _render() -> None:
    theme.inject_scroll_restore()
    pngs = sorted(data.FIGURES_DIR.glob("*.png"))
    if not pngs:
        st.info("No figures found — run the pipeline to generate them.")
    else:
        for png in pngs:
            st.image(str(png), caption=png.stem, width="stretch")


_render()
