"""Figures — the existing matplotlib gallery (figures/output/*.png). No
reason to rebuild these as interactive charts; they already work well as
static single-day visual summaries."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

import data

st.title("🖼️ Figures")
st.caption("Generated by `figures/generate()` at the end of every run — reflects the most recent run's date.")

pngs = sorted(data.FIGURES_DIR.glob("*.png"))
if not pngs:
    st.info("No figures found — run the pipeline to generate them.")
else:
    cols = st.columns(2)
    for i, png in enumerate(pngs):
        with cols[i % 2]:
            st.image(str(png), caption=png.stem, width="stretch")
